#
# jekyll-pub.yml
#
# Publish the Jekyll site whenever 'deploy' is pushed
#

name: Jekyll Deploy

on:
  push:
    branches:
    - deploy

jobs:
  deploy-site:
    if: github.repository == 'MarlinFirmware/MarlinDocumentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
